[package]
name = "arena_war"
version = "0.1.0"
edition = "2021"

[lib]
name = "arena_war"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

[features]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]
default = []
